import{describe,expect,it}from'vitest';import{createKestrelEncounterFixture,createTwoRoomFixture}from'../../src/debug/fixtures';import{allocateId}from'../../src/engine/entities';import type{WorldState}from'../../src/engine/model/state';import{CAN_SEE_INVISIBLE,IS_RUNNING}from'../../src/engine/rules/flags';import{ringCombatBonus}from'../../src/engine/rules/rings';import{GameSession}from'../../src/engine/session';import{restoreGame}from'../../src/persistence/save';
function ring(state:WorldState,definitionId:string,magnitude=0):string{const id=allocateId(state);state.entities[id]={kind:'item',id,definitionId,category:'ring',location:{kind:'pack',owner:'player'},quantity:1,flags:0,group:0,label:null,magnitude};state.player.packOrder.push(id);return id;}
describe('ring identities and passive effects',()=>{
 it('assigns distinct source stones and stores their added worth',()=>{const entries=createTwoRoomFixture(501).identification.filter(value=>value.definitionId.startsWith('ring.'));expect(entries).toHaveLength(14);expect(new Set(entries.map(value=>value.appearanceId)).size).toBe(14);expect(entries.every(value=>typeof value.worth==='number'&&value.worth>0)).toBe(true);});
 it('applies and removes strength and see-invisible rings',()=>{const state=createTwoRoomFixture(502);const strength=ring(state,'ring.add-strength',2);const sight=ring(state,'ring.see-invisible');const session=new GameSession(state);
  session.submit({expectedRevision:0,action:{type:'equip',itemId:strength,slot:'leftRing'}});session.submit({expectedRevision:1,action:{type:'equip',itemId:sight,slot:'rightRing'}});let after=session.exportState();expect(after.player.stats.strength).toBe(12);expect(after.player.flags&CAN_SEE_INVISIBLE).not.toBe(0);
  session.submit({expectedRevision:2,action:{type:'unequip',slot:'leftRing'}});session.submit({expectedRevision:3,action:{type:'unequip',slot:'rightRing'}});after=session.exportState();expect(after.player.stats.strength).toBe(10);expect(after.player.flags&CAN_SEE_INVISIBLE).toBe(0);expect(restoreGame(after).exportState()).toEqual(after);});
 it('aggravates monsters immediately and charges ring-specific food use',()=>{const state=createKestrelEncounterFixture(503);const aggravate=ring(state,'ring.aggravate-monster');const regen=ring(state,'ring.regeneration');state.entities.e1!.flags&=~IS_RUNNING;const session=new GameSession(state);
  session.submit({expectedRevision:0,action:{type:'equip',itemId:aggravate,slot:'leftRing'}});expect((session.exportState().entities.e1 as{flags:number}).flags&IS_RUNNING).not.toBe(0);
  session.submit({expectedRevision:1,action:{type:'equip',itemId:regen,slot:'rightRing'}});const before=session.exportState().timing.foodLeft;session.submit({expectedRevision:2,action:{type:'rest'}});expect(session.exportState().timing.foodLeft).toBe(before-3);});
 it('provides per-hand protection, dexterity, and damage combat totals',()=>{const state=createTwoRoomFixture(504);const hit=ring(state,'ring.dexterity',3);const damage=ring(state,'ring.increase-damage',2);state.player.equipment.leftRing=hit;state.player.equipment.rightRing=damage;
  expect(ringCombatBonus(state,'hit')).toBe(3);expect(ringCombatBonus(state,'damage')).toBe(2);expect(ringCombatBonus(state,'armor')).toBe(0);});
});
